# yaml file for docker
sudo: required
language: python
services:
- docker

script:
- docker image build -t destire/dockerq4 .

after_success:
  #log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  - docker push destire/dockerq4
  #test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dtest"
  env: "Dtest-env"
  bucket_name: "elasticbeanstalk-us-east-2-047340625628"
  on:
    branch: Docker
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY